// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZhiHu.Photo.Server.DatabaseContext;

#nullable disable

namespace ZhiHu.Photo.Server.Migrations
{
    [DbContext(typeof(PhotoDbContext))]
    [Migration("20221030112119_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZhiHu.Photo.Server.Entities.AnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnswerCreatedTimeStamp")
                        .HasColumnType("int");

                    b.Property<int>("AnswerUpdatedTimeStamp")
                        .HasColumnType("int");

                    b.Property<bool>("Attachment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Excerpt")
                        .HasColumnType("longtext");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MediaCount")
                        .HasColumnType("longtext");

                    b.Property<string>("NikeName")
                        .HasColumnType("longtext");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<int>("ThanksCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("VoteUpCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Answer");
                });
#pragma warning restore 612, 618
        }
    }
}
