// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZhiHu.Photo.Server.DatabaseContext;

#nullable disable

namespace ZhiHu.Photo.Server.Migrations
{
    [DbContext(typeof(PhotoDbContext))]
    [Migration("20231201012812_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZhiHu.Photo.Server.Entities.AnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnswerCreatedTimeStamp")
                        .HasColumnType("int");

                    b.Property<int>("AnswerUpdatedTimeStamp")
                        .HasColumnType("int");

                    b.Property<bool>("Attachment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Excerpt")
                        .HasColumnType("longtext");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MediaCount")
                        .HasColumnType("int");

                    b.Property<string>("NextPageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("NikeName")
                        .HasColumnType("longtext");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<int>("ThanksCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("VoteUpCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("ZhiHu.Photo.Server.Entities.ImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("VideoId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ZhiHu.Photo.Server.Entities.VideoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("HUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("LUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("ZhiHu.Photo.Server.Entities.ImageEntity", b =>
                {
                    b.HasOne("ZhiHu.Photo.Server.Entities.AnswerEntity", "Answer")
                        .WithMany("Images")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZhiHu.Photo.Server.Entities.VideoEntity", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId");

                    b.Navigation("Answer");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ZhiHu.Photo.Server.Entities.AnswerEntity", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
